### ISSUE TITLE
A way to get the Test Status from QR-Code Data but without the App?

### ISSUE THREAD

**Issue by cracker0dks** [corona-warn-app/cwa-verification-server#240]
If we decode the CWA QR-Code base64 Date from a Test result page, we get something like: ```{
      "timestamp":1625739254,
      "salt":"17C952571EBFBE2093B9F23D11DBFA50",
      "hash":"3ba339b77bba178e79fb3dfd6d0d8109b8a2e0d9f01c9b57c778c5ab73238e83"
}```
I there a way to get the test status from this Data without the CWA ? 

The Background: We (At our University) want to implement a way to verify the 3G Status from our students and add them to the checkIn App (A diffrent App). The QR-Code given from the test stations are plain urls and have different Spezifikation on how to extract test results, but if we could use the CWA QR-Code to get the status, we would be good to go. 

Thanks for help

**Comment by daniel-eder** [comment]
@cracker0dks please visit https://github.com/eu-digital-green-certificates/dgc-overview, the EU project that contains sample code on how to verify QR codes. Please note that in order to have access to the public keys necessary to validate the signature of a QR code you need to contact your public health authority.
