### ISSUE TITLE
Please write useful comments or no comments

### ISSUE THREAD

**Issue by HolgerMayer** [corona-warn-app/cwa-verification-server#40]
## Current Implementation

If you write a comment in code it should not be a redundant statement.

Especially bad example is OpenApiConfig.java

Another more basic example is HashedGuid.java. What does the class comment tell us?

For further reference see Robert C. Martin , Clean Code. Chapter 4 Commments

## Suggested Enhancement

Write why a class or function exists.
Write what assumptions are made.

## Expected Benefits

Better maintainable code.

**Comment by zhedar** [comment]
I just had a look at the architecture documentation. We should probably use the descriptions from the [core entities section](https://github.com/corona-warn-app/cwa-verification-server/blob/master/docs/architecture-overview.md#core-entities) and add them to the javadoc. Otherwise we could like to the documentation page from the javadoc and to avoid a lot of text duplication.
Any thoughts on this?
