### ISSUE TITLE
Teletan hash stored without salting

### ISSUE THREAD

**Issue by oiime** [corona-warn-app/cwa-verification-server#74]
## Current Implementation

Teletan is described as an integer, making it very cheap to generate a rainbow table for the purpose of circumventing the hashes quickly

## Suggested Enhancement

consider adding a salt to the hash or alternatively rely on the client to provide a salted hash 

## Expected Benefits

Making it marginally harder to compromise the entire dataset

**Comment by alstiefel** [comment]
teleTAN is defined in 
https://github.com/corona-warn-app/cwa-verification-server/blob/master/docs/architecture-overview.md#core-entities

it is a 7 char string, which we will extend in the next days to a 9+1 char string.

we can not salt the teleTAN, because it exists with no context and we would not know which salt to apply when a user enters a teleTAN.

As documented therefore there is no salt, no pepper.
https://github.com/corona-warn-app/cwa-verification-server/blob/master/docs/architecture-overview.md#core-entities

Documentation could be a bit more detailed on the issue.
